apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "pulsed.fullname" . }}
  labels: {{ include "pulsed.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "pulsed.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "pulsed.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "pulsed.fullname" . }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: pulsed
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PULSED_DB
              value: {{ .Values.db.path }}
            - name: PULSED_HTTP
              value: ":{{ .Values.web.port }}"
            - name: PULSED_GOSSIP
              value: ":{{ .Values.gossip.port }}"
            - name: PULSED_WEB
              value: "{{ .Values.web.enabled }}"
            - name: PULSED_SEEDS
              value: "pulsed-headless.{{ .Release.Namespace }}.svc.cluster.local"
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
            - name: gossip-tcp
              containerPort: {{ .Values.gossip.port }}
              protocol: TCP
            - name: gossip-udp
              containerPort: {{ .Values.gossip.port }}
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources: {{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: state
              mountPath: /var/lib/pulsed
      volumes:
        - name: state
          emptyDir: {}
