apiVersion: v1
kind: Service
metadata:
  name: pulsed-headless
spec:
  clusterIP: None
  selector: {{ include "pulsed.selectorLabels" . | nindent 4 }}
  ports:
    - name: gossip-tcp
      port: {{ .Values.gossip.port }}
      protocol: TCP
    - name: gossip-udp
      port: {{ .Values.gossip.port }}
      protocol: UDP
